### ISSUE TITLE
Spin off ToO

### ISSUE THREAD

**Issue by robertdstein** [skyportal/gwemopt#123]
Right now the https://github.com/skyportal/gwemopt/tree/2baea8ffce2853560d1ee3fde7a97bf5e957d3e8/ToO directory contains a totally independent python package, which just happens to have gwemopt as a dependency. There is no reason that x/y/z random user should need to download all that code, just to use gwemopt. After discussion with Michael, I suggest should spin that off as a separate package, with its own maintainers etc, and keep the gwemopt repo for only direct gwemopt code.

**Comment by Theodlz** [comment]
Agreed! @mcoughlin @robertdstein could one of you tell me exactly what you expect this package to do? 
Just trying to figure out if you just want me to copy/paste this in another git repo, or if some refactoring/clean-up is needed as well.

**Comment by robertdstein** [comment]
I have no idea what it's doing, other than that it's related to Grandma. I'm not sure if it's even used at all.

**Comment by mcoughlin** [comment]
@Theodlz yes exactly. I think it just needs to move that part of the code needs to move into the grandma-collaboration namespace.
