### ISSUE TITLE
Always do Observability?

### ISSUE THREAD

**Issue by robertdstein** [skyportal/gwemopt#127]
It appears that "--doObservability" makes a big difference to the generated schedules. It does not take very long. If it more correct behaviour, should we just require it? There are a ton of if statements related to this in the code, and the "reasonable default" is not clear to me.

**Comment by robertdstein** [comment]
(cc #90 )

**Comment by robertdstein** [comment]
Per additional discussion, it is not clear that the functionality is actually useful for plans, and it is definitely true that the function was not used in O3. Perhaps it should be purely a plotting feature. Needs investigation.

**Comment by mcoughlin** [comment]
Removed from the codebase.
