### ISSUE TITLE
Tesslation file

### ISSUE THREAD

**Issue by santier14** [skyportal/gwemopt#135]
I have a comment on dorado-scheduling-skygrid. When I do dorado-scheduling-skygrid --area "49 deg2"

I got a file which have overlaps in terms of tesslation (sorry I can't attached pdf in this issue) and when i do it via gwemopt (the old version), the tesslation file is very different. I would like to understand why.

Also when I run gwemopt with the file from dorado, it is crashing my gwemopt

as /home/antier/anaconda3/envs/gwemopt/lib/python3.9/site-packages/gwemopt-0+unknown-py3.9.egg/gwemopt/tiles.py:353: RuntimeWarning: invalid value encountered in true_divide
  ranked_tile_probs = ranked_tile_probs / np.nansum(ranked_tile_probs)
Generating segments for tiles...
/home/antier/anaconda3/envs/gwemopt/lib/python3.9/site-packages/gwemopt-0+unknown-py3.9.egg/gwemopt/segments.py:420: RuntimeWarning: invalid value encountered in arcsin
  dist = 2.0*np.arcsin( np.sqrt( np.sin(delt_lat/2.0)**2 + \

So be said, i think there is some issue with the tesslation file

**Comment by mcoughlin** [comment]
@santier14 Could you try a few different of the options for the tesselation style? You can see the options if you run dorado with --help. @robertdstein I am not sure if you know what might be going on with that error?

**Comment by robertdstein** [comment]
I'm not sure if your recent PR fixed this problem @mcoughlin , but beyond that I have no idea. I have not personally touched the tessellation file stuff.

**Comment by mcoughlin** [comment]
I am closing this for now and can maybe update the tesselation file in a future PR.
