### ISSUE TITLE
Lines out of loop in samplers.py

### ISSUE THREAD

**Issue by JTBaird91** [skyportal/gwemopt#65]
Lines 254-259 of samplers.py need to be adjusted out one space to align with the for loop iterating over each tile ID. Otherwise the 'greedy' schedule only returns a dictionary with the last tile attributes saved and all other tiles entries empty.

**Comment by mcoughlin** [comment]
We don't use samplers much anymore. Can you submit a quick PR?

**Comment by JTBaird91** [comment]
Ah ok. Yes I am currently just exploring the code and the default schedule was 'greedy'. I will submit and make sure to request a different schedule at runtime.
